"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { currentUser } from "@clerk/nextjs/server"; 
import { sendNotification } from "@/lib/notifications"; 
// REMOVED: import { generateCustomerPO } ...

type CartItem = {
  productId: string;
  vendorId: string;
  quantity: number;
  price: number;
  productName?: string; 
  image?: string;       
};

type Address = {
  name: string;
  street: string;
  city: string;
  state: string;
  postalCode: string;
  phone: string;
};

export async function placeOrder(userId: string, cartItems: CartItem[], totalAmount: number, address: Address) {
  try {
    if (!address) throw new Error("Delivery address is missing.");

    // 1. Fetch User Email from Clerk
    const user = await currentUser();
    const userEmail = user?.emailAddresses[0]?.emailAddress || "";

    console.log("🛒 STARTING CHECKOUT: Processing", cartItems.length, "items...");

    // START TRANSACTION
    const result = await prisma.$transaction(async (tx) => {
      
      // 2. Create Order
      const newOrder = await tx.order.create({
        data: {
          customerId: userId,
          customerName: address.name,
          customerEmail: userEmail, 
          customerPhone: address.phone,
          totalAmount: totalAmount,
          status: "PENDING",
          address: JSON.stringify(address),
          
          items: {
            create: cartItems.map((item) => ({
              productId: item.productId,
              vendorId: item.vendorId, 
              quantity: item.quantity,
              price: item.price
            }))
          }
        }
      });

      // 3. DEDUCT STOCK
      for (const item of cartItems) {
        console.log(`🔻 DECREMENTING Stock for Item ${item.productId} by ${item.quantity}`);
        await tx.product.update({
          where: { id: item.productId },
          data: {
            quantity: { decrement: item.quantity } 
          }
        });
      }

      return newOrder;
    });

    // REMOVED: await generateCustomerPO(result.id);
    // The PO will now be generated by the Admin when they "Approve" the order.

    // --- 4. SEND NOTIFICATIONS ---

    // A. Notify Customer
    await sendNotification("ORDER_PLACED", {
      toEmail: userEmail,
      toPhone: address.phone,
      name: address.name,
      orderId: result.id
    });

    // B. Notify Vendor(s)
    const uniqueVendorIds = [...new Set(cartItems.map(item => item.vendorId))];

    for (const vendorId of uniqueVendorIds) {
      const vendor = await prisma.vendorProfile.findUnique({
        where: { userId: vendorId },
        select: { email: true, phone: true, fullName: true }
      });

      if (vendor) {
        await sendNotification("ORDER_PLACED", {
          toEmail: vendor.email,
          toPhone: vendor.phone,
          name: vendor.fullName,
          orderId: result.id,
          extraMessage: "You have received a new order! Check your dashboard."
        });
      }
    }

    console.log("✅ ORDER SUCCESS. Inventory updated & Notifications sent.");
    
    revalidatePath("/vendor/inventory");
    revalidatePath("/vendor/orders");
    revalidatePath("/browse");
    
    return { success: true, orderId: result.id };

  } catch (error) {
    console.error("❌ ORDER FAILED:", error);
    return { success: false, error: (error as Error).message || "Order failed" };
  }
}